In [1]:
import numpy as np
import pandas as pd

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
# !cp /content/drive/MyDrive/Amazon_dataset.csv /content/Amazon_dataset.csv

In [4]:
!wget https://cdn.ibnukhaidar-pi.com/Amazon_dataset.csv

--2025-05-13 17:48:24--  https://cdn.ibnukhaidar-pi.com/Amazon_dataset.csv
Resolving cdn.ibnukhaidar-pi.com (cdn.ibnukhaidar-pi.com)... 104.21.72.162, 172.67.153.36, 2606:4700:3033::6815:48a2, ...
Connecting to cdn.ibnukhaidar-pi.com (cdn.ibnukhaidar-pi.com)|104.21.72.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 70699689 (67M) [text/csv]
Saving to: ‘Amazon_dataset.csv’

Amazon_dataset.csv  100%[===================>]  67.42M   188MB/s    in 0.4s

2025-05-13 17:48:24 (188 MB/s) - ‘Amazon_dataset.csv’ saved [70699689/70699689]

In [5]:
df = pd.read_csv('Amazon_dataset.csv')

In [6]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,stock
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255",32999,58990,0
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948",46490,75990,0
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206",34490,61990,0
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,37990,68990,0
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,34490,67790,0

### cek apakah ada duplikat dalam nama

In [7]:
nama_duplikat = df[df.duplicated(subset=['name'], keep=False)]
print(nama_duplikat)

                                                     name     main_category  \
0       Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...        appliances
1       LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...        appliances
2       LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...        appliances
3       LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...        appliances
4       Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...        appliances
...                                                   ...               ...
551562  More & More Dancing Panda Printed Unisex Hoodi...  sports & fitness
551568                              Adidas Men's Standard  sports & fitness
551572                Amazon Brand - Symactive Men Shorts  sports & fitness
551578                              Puma Women Sweatshirt  sports & fitness
551583                                    Puma Men Shorts  sports & fitness

            sub_category ratings no_of_ratings discount_price actual_price  \
0       Air Conditioners     4.2         2,255          32999        58990
1       Air Conditioners     4.2         2,948          46490        75990
2       Air Conditioners     4.2         1,206          34490        61990
3       Air Conditioners     4.0            69          37990        68990
4       Air Conditioners     4.1           630          34490        67790
...                  ...     ...           ...            ...          ...
551562              Yoga     3.9           271            799         2499
551568              Yoga     3.4            16           1349         4299
551572              Yoga     5.0             2         655,04         2399
551578              Yoga     NaN           NaN           1439         2999
551583              Yoga     4.4            37            NaN          NaN

        stock
0           0
1           0
2           0
3           0
4           0
...       ...
551562      0
551568      0
551572      0
551578      0
551583      0

[235795 rows x 8 columns]

### cek tipe data dari dataframe

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 551585 entries, 0 to 551584
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            551585 non-null  object
 1   main_category   551585 non-null  object
 2   sub_category    551585 non-null  object
 3   ratings         375791 non-null  object
 4   no_of_ratings   375791 non-null  object
 5   discount_price  490422 non-null  object
 6   actual_price    533772 non-null  object
 7   stock           551585 non-null  int64
dtypes: int64(1), object(7)
memory usage: 33.7+ MB

### menghapus duplikat nama

In [9]:
df.drop_duplicates(subset=['name'], keep='first', inplace=True)

In [10]:
df.reset_index(drop=True, inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396210 entries, 0 to 396209
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            396210 non-null  object
 1   main_category   396210 non-null  object
 2   sub_category    396210 non-null  object
 3   ratings         267648 non-null  object
 4   no_of_ratings   267648 non-null  object
 5   discount_price  350450 non-null  object
 6   actual_price    384273 non-null  object
 7   stock           396210 non-null  int64
dtypes: int64(1), object(7)
memory usage: 24.2+ MB

### sudah berkurang dari 500k menjadi 396k

In [12]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,stock
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255",32999,58990,0
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948",46490,75990,0
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206",34490,61990,0
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,37990,68990,0
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,34490,67790,0

### hitung jumlah row atau baris yang ada pada dataframe

In [13]:
df.shape[0]

396210

### cek missing values di kolom rating

In [14]:
# Check for missing values in 'ratings' columns
missing_ratings = df['ratings'].isna().sum()

print(f"Missing values in 'ratings': {missing_ratings}")

Missing values in 'ratings': 128562

### mengisi missing value dengan float dari 1.0 ke 5.0

In [15]:
df['ratings'] = df['ratings'].apply(lambda x: np.random.uniform(1.0, 5.0) if pd.isna(x) else x)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396210 entries, 0 to 396209
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            396210 non-null  object
 1   main_category   396210 non-null  object
 2   sub_category    396210 non-null  object
 3   ratings         396210 non-null  object
 4   no_of_ratings   267648 non-null  object
 5   discount_price  350450 non-null  object
 6   actual_price    384273 non-null  object
 7   stock           396210 non-null  int64
dtypes: int64(1), object(7)
memory usage: 24.2+ MB

### cek missing value lagi

In [17]:
# Check for missing values in 'ratings' columns
missing_ratings = df['ratings'].isna().sum()

print(f"Missing values in 'ratings': {missing_ratings}")

Missing values in 'ratings': 0

### sudah hilang untuk missing value dari ratings

In [18]:
df['ratings'] = pd.to_numeric(df['ratings'], errors='coerce')

In [19]:
df['ratings'] = df['ratings'].astype(float)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396210 entries, 0 to 396209
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            396210 non-null  object
 1   main_category   396210 non-null  object
 2   sub_category    396210 non-null  object
 3   ratings         390654 non-null  float64
 4   no_of_ratings   267648 non-null  object
 5   discount_price  350450 non-null  object
 6   actual_price    384273 non-null  object
 7   stock           396210 non-null  int64
dtypes: float64(1), int64(1), object(6)
memory usage: 24.2+ MB

In [21]:
df['ratings'] = df['ratings'].apply(lambda x: np.random.uniform(1.0, 5.0) if pd.isna(x) else x)

In [22]:
df['ratings'] = df['ratings'].apply(lambda x: np.round(np.ceil(x * 10) / 10, 1))

In [23]:
# Check for missing values in 'ratings' columns
missing_ratings = df['ratings'].isna().sum()

print(f"Missing values in 'ratings': {missing_ratings}")

Missing values in 'ratings': 0

In [24]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,stock
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255",32999,58990,0
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948",46490,75990,0
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206",34490,61990,0
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,37990,68990,0
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,34490,67790,0

In [25]:
df['no_of_ratings'].head()

0    2,255
1    2,948
2    1,206
3       69
4      630
Name: no_of_ratings, dtype: object

### cek jika ada missing value ada no_of_ratings

In [26]:
nan_no_of_ratings = df[df['no_of_ratings'].isna()]
print(nan_no_of_ratings)

                                                     name     main_category  \
24      Lloyd 1.5 Ton 3 Star Fixed Speed Window Ac (Co...        appliances
50      Samsung 1 Ton 5 Star Inverter Split AC (Copper...        appliances
57      Haier 1.5 Ton 3 Star Frost Self Clean Inverter...        appliances
69      Lloyd 2.0 Ton 3 Star Inverter Split Ac (5 In 1...        appliances
73      Voltas 1.5 Ton 3 Star, Fixed Speed Window AC (...        appliances
...                                                   ...               ...
396148  The Yogis Iyengar Wall Yoga Ropes full Set of ...  sports & fitness
396150  Men's Regular FIT Dont Quit Printed Cotton Hoodie  sports & fitness
396197  Amazon Brand - Symactive Men's Activewear Gym ...  sports & fitness
396201  Just rider Arm Sleeves UV Protection for Drivi...  sports & fitness
396204  Obsessions Reversible Printed Yoga Mat,Anti-Sl...  sports & fitness

            sub_category  ratings no_of_ratings discount_price actual_price  \
24      Air Conditioners      4.9           NaN          27440        47990
50      Air Conditioners      2.0           NaN          36999        57990
57      Air Conditioners      2.2           NaN          32990        64000
69      Air Conditioners      3.2           NaN          46000        77990
73      Air Conditioners      3.6           NaN          29990        42990
...                  ...      ...           ...            ...          ...
396148              Yoga      5.0           NaN           1699         1999
396150              Yoga      5.0           NaN            549          899
396197              Yoga      4.1           NaN            699         2199
396201              Yoga      2.1           NaN            219          699
396204              Yoga      4.7           NaN           1320         1650

        stock
24          0
50          0
57          0
69          0
73          0
...       ...
396148      0
396150      0
396197      0
396201      0
396204      0

[128562 rows x 8 columns]

In [27]:
df['no_of_ratings'].tail()

396205    6
396206    9
396207    2
396208    1
396209    5
Name: no_of_ratings, dtype: object

In [28]:
df['no_of_ratings'] = df['no_of_ratings'].str.replace(',', '')

In [29]:
# Define a function to replace specific strings with random integers
def replace_with_random_int(x):
    if isinstance(x, str) and (
        x.startswith("Usually dispatched") or x.startswith("Only") or x.startswith("Free") or x.startswith("This item") or x.startswith("FREE Delivery")
    ):
        return np.random.randint(1, 2501)
    else:
        return x

# Apply the function to the 'no_of_ratings' column
df['no_of_ratings'] = df['no_of_ratings'].apply(replace_with_random_int)

In [30]:
df['no_of_ratings'] = pd.to_numeric(df['no_of_ratings'], errors='coerce')

In [31]:
df['no_of_ratings'] = df['no_of_ratings'].apply(lambda x: np.random.randint(1, 2501) if pd.isna(x) else x)

In [32]:
df['no_of_ratings'] = df['no_of_ratings'].astype(int)

In [33]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,stock
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,2255,32999,58990,0
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,2948,46490,75990,0
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,1206,34490,61990,0
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,37990,68990,0
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,34490,67790,0

In [34]:
nan_no_of_ratings = df[df['no_of_ratings'].isnull()]
print(nan_no_of_ratings)

Empty DataFrame
Columns: [name, main_category, sub_category, ratings, no_of_ratings, discount_price, actual_price, stock]
Index: []

untuk data no of ratings sudah hilang

### cek missing value di discount_price

In [35]:
nan_discount_price = df[df['discount_price'].isna()]
print(nan_discount_price)

                                                     name     main_category  \
76      LG 1.5 Ton 3 Star Hot & Cold DUAL Inverter Spl...        appliances
100     Hitachi 1.5 Ton 5 Star Inverter Split AC (Copp...        appliances
113     Panasonic 1.5 Ton 4 Star Wi-Fi Twin-Cool Inver...        appliances
125     Hitachi 1.5 Ton 5 Star Window AC (Copper, Dust...        appliances
136     Portable Air Conditioner,Office Air Conditione...        appliances
...                                                   ...               ...
396159  Head HBS-1091 Polyester Badminton Shorts, XX-S...  sports & fitness
396164  Nivia 2434 Polyester Women Jacket, X-Large (Tu...  sports & fitness
396173  Nivia 2367-3 Hydra-2 Polyester Training Tee, A...  sports & fitness
396174  Nivia 2365-3 Hydra-1 Polyester Training Tee, A...  sports & fitness
396196       Adidas Women's Cotton Hooded Neck Sweatshirt  sports & fitness

            sub_category  ratings  no_of_ratings discount_price actual_price  \
76      Air Conditioners      4.0            265            NaN          NaN
100     Air Conditioners      3.8            748            NaN          NaN
113     Air Conditioners      4.5            195            NaN          NaN
125     Air Conditioners      2.7             10            NaN        49300
136     Air Conditioners      3.2            303            NaN         7250
...                  ...      ...            ...            ...          ...
396159              Yoga      2.8              4            NaN          699
396164              Yoga      5.0              2            NaN         1433
396173              Yoga      4.0              8            NaN          680
396174              Yoga      3.2              7            NaN          507
396196              Yoga      3.9              3            NaN         4799

        stock
76          0
100         0
113         0
125         0
136         0
...       ...
396159      0
396164      0
396173      0
396174      0
396196      0

[45760 rows x 8 columns]

In [36]:
df['discount_price'] = df['discount_price'].apply(lambda x: np.random.randint(1, 2501) if pd.isna(x) else x)

In [37]:
df['discount_price'] = df['discount_price'].str.replace(',', '')

In [38]:
df['discount_price'] = df['discount_price'].apply(lambda x: np.random.randint(1, 2501) if pd.isna(x) else x)

In [39]:
df['discount_price'] = df['discount_price'].astype(int)

In [40]:
df['discount_price'] = df['discount_price'].apply(lambda x: int(np.ceil(x)) if isinstance(x, float) else x)

In [41]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,stock
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,2255,32999,58990,0
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,2948,46490,75990,0
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,1206,34490,61990,0
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,37990,68990,0
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,34490,67790,0

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396210 entries, 0 to 396209
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            396210 non-null  object
 1   main_category   396210 non-null  object
 2   sub_category    396210 non-null  object
 3   ratings         396210 non-null  float64
 4   no_of_ratings   396210 non-null  int64
 5   discount_price  396210 non-null  int64
 6   actual_price    384273 non-null  object
 7   stock           396210 non-null  int64
dtypes: float64(1), int64(3), object(4)
memory usage: 24.2+ MB

### cek missing value untuk missing price

In [43]:
actual_price_missing = df[df['actual_price'].isna()]
print(actual_price_missing)

                                                     name     main_category  \
76      LG 1.5 Ton 3 Star Hot & Cold DUAL Inverter Spl...        appliances
100     Hitachi 1.5 Ton 5 Star Inverter Split AC (Copp...        appliances
113     Panasonic 1.5 Ton 4 Star Wi-Fi Twin-Cool Inver...        appliances
143     Daikin 1.5 Ton 4 Star Hot & Cold Heat Pump Inv...        appliances
145     LG 1.5 Ton 5 Star AI DUAL Inverter Wi-Fi Split...        appliances
...                                                   ...               ...
396017  Charged Energy-004 Interlock Knit Hexagon Embo...  sports & fitness
396034                           Adidas Men's Flat Jacket  sports & fitness
396038  Workout Knee Cushion, Crush Resistance Compact...  sports & fitness
396064  Tom & Jerry by Wear Your Mind Unisex-Child Hoo...  sports & fitness
396071                Mode By Red Tape Women Black Hoodie  sports & fitness

            sub_category  ratings  no_of_ratings  discount_price actual_price  \
76      Air Conditioners      4.0            265             822          NaN
100     Air Conditioners      3.8            748            1274          NaN
113     Air Conditioners      4.5            195            1136          NaN
143     Air Conditioners      3.7             27              84          NaN
145     Air Conditioners      4.7             34            2211          NaN
...                  ...      ...            ...             ...          ...
396017              Yoga      1.3           1395             294          NaN
396034              Yoga      4.0             11            1772          NaN
396038              Yoga      1.9            825            1090          NaN
396064              Yoga      2.0           1461             689          NaN
396071              Yoga      3.6              3             731          NaN

        stock
76          0
100         0
113         0
143         0
145         0
...       ...
396017      0
396034      0
396038      0
396064      0
396071      0

[11937 rows x 8 columns]

In [44]:
df['actual_price'] = df['actual_price'].apply(lambda x: np.random.randint(1, 50001) if pd.isna(x) else x)

In [45]:
df['actual_price'] = df['actual_price'].astype(str).str.replace(',', '', regex=False)

In [46]:
df['actual_price'] = pd.to_numeric(df['actual_price'], errors='coerce')

In [47]:
df['actual_price'] = df['actual_price'].apply(lambda x: np.random.randint(1, 50001) if pd.isna(x) else x)

In [48]:
df['actual_price'] = df['actual_price'].astype(int)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396210 entries, 0 to 396209
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            396210 non-null  object
 1   main_category   396210 non-null  object
 2   sub_category    396210 non-null  object
 3   ratings         396210 non-null  float64
 4   no_of_ratings   396210 non-null  int64
 5   discount_price  396210 non-null  int64
 6   actual_price    396210 non-null  int64
 7   stock           396210 non-null  int64
dtypes: float64(1), int64(4), object(3)
memory usage: 24.2+ MB

In [50]:
actual_price_missing = df[df['actual_price'].isna()]
print(actual_price_missing)

Empty DataFrame
Columns: [name, main_category, sub_category, ratings, no_of_ratings, discount_price, actual_price, stock]
Index: []

### randomize stock

In [51]:
df['stock'] = df['stock'].apply(lambda x: np.random.randint(1, 25001) if x == 0 else x)

In [53]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price,stock
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,2255,32999,58990,20143
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,2948,46490,75990,23179
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,1206,34490,61990,15004
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,37990,68990,21576
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,34490,67790,4627

In [54]:
df.to_csv('Amazon_dataset_cleaned.csv', index=True)