In [1]:
#!kaggle datasets download lokeshparab/amazon-products-dataset

In [2]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('dataset/amazon_product_worked.csv')
df.head()

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255","₹32,999","₹58,990"
1,1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948","₹46,490","₹75,990"
2,2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206","₹34,490","₹61,990"
3,3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,"₹37,990","₹68,990"
4,4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790"

In [6]:
df = df.drop(['Unnamed: 0', 'image', 'link'], axis=1)
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,"₹34,490","₹67,790"

In [8]:
df.tail(10)

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
551575,"Just Rider Compression Clothing (XXL, Black)",sports & fitness,Yoga,3.0,2,₹228,₹799
551576,PANCHTATAVA Yoga Mat Cover with Adjustable Sho...,sports & fitness,Yoga,4.5,2,₹245,"₹1,499"
551577,"Obsessions Reversible Printed Yoga Mat,Anti-Sl...",sports & fitness,Yoga,NaN,NaN,"₹1,320","₹1,650"
551578,Puma Women Sweatshirt,sports & fitness,Yoga,NaN,NaN,"₹1,439","₹2,999"
551579,BE SAVAGE Pink I Purple You Hoodie Suitable fo...,sports & fitness,Yoga,4.6,6,₹711,₹999
551580,Adidas Regular Fit Men's Track Tops,sports & fitness,Yoga,3.2,9,"₹3,449","₹4,599"
551581,Redwolf Noice Toit Smort - Hoodie (Black),sports & fitness,Yoga,2.0,2,"₹1,199","₹1,999"
551582,Redwolf Schrute Farms B&B - Hoodie (Navy Blue),sports & fitness,Yoga,4.0,1,"₹1,199","₹1,999"
551583,Puma Men Shorts,sports & fitness,Yoga,4.4,37,NaN,NaN
551584,Mothercare Printed Cotton Elastane Girls Infan...,sports & fitness,Yoga,4.6,5,"₹1,039","₹1,299"

In [9]:
empty_actual_price = df[df['actual_price'].isnull()]
empty_actual_price

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
76,LG 1.5 Ton 3 Star Hot & Cold DUAL Inverter Spl...,appliances,Air Conditioners,4.0,265,NaN,NaN
100,Hitachi 1.5 Ton 5 Star Inverter Split AC (Copp...,appliances,Air Conditioners,3.8,748,NaN,NaN
114,Panasonic 1.5 Ton 4 Star Wi-Fi Twin-Cool Inver...,appliances,Air Conditioners,4.5,195,NaN,NaN
144,Daikin 1.5 Ton 4 Star Hot & Cold Heat Pump Inv...,appliances,Air Conditioners,3.7,27,NaN,NaN
146,LG 1.5 Ton 5 Star AI DUAL Inverter Wi-Fi Split...,appliances,Air Conditioners,4.7,34,NaN,NaN
...,...,...,...,...,...,...,...
551371,"Workout Knee Cushion, Crush Resistance Compact...",sports & fitness,Yoga,NaN,NaN,NaN,NaN
551402,Tom & Jerry by Wear Your Mind Unisex-Child Hoo...,sports & fitness,Yoga,NaN,NaN,NaN,NaN
551410,Mode By Red Tape Women Black Hoodie,sports & fitness,Yoga,3.6,3,NaN,NaN
551471,Campus Sutra Women Printed Hoodie,sports & fitness,Yoga,3.7,8,NaN,NaN
551583,Puma Men Shorts,sports & fitness,Yoga,4.4,37,NaN,NaN

In [11]:
empty_discount_price = df[df['discount_price'].isnull()]
empty_discount_price

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
76,LG 1.5 Ton 3 Star Hot & Cold DUAL Inverter Spl...,appliances,Air Conditioners,4.0,265,NaN,NaN
100,Hitachi 1.5 Ton 5 Star Inverter Split AC (Copp...,appliances,Air Conditioners,3.8,748,NaN,NaN
114,Panasonic 1.5 Ton 4 Star Wi-Fi Twin-Cool Inver...,appliances,Air Conditioners,4.5,195,NaN,NaN
126,"Hitachi 1.5 Ton 5 Star Window AC (Copper, Dust...",appliances,Air Conditioners,2.7,10,NaN,"₹49,300"
137,"Portable Air Conditioner,Office Air Conditione...",appliances,Air Conditioners,3.2,303,NaN,"₹7,250"
...,...,...,...,...,...,...,...
551535,"Nivia 2367-3 Hydra-2 Polyester Training Tee, A...",sports & fitness,Yoga,4.0,8,NaN,₹680
551536,"Nivia 2365-3 Hydra-1 Polyester Training Tee, A...",sports & fitness,Yoga,3.2,7,NaN,₹507
551542,Adidas Men's Flat,sports & fitness,Yoga,NaN,NaN,NaN,"₹2,699"
551567,Adidas Women's Cotton Hooded Neck Sweatshirt,sports & fitness,Yoga,3.9,3,NaN,"₹4,799"
551583,Puma Men Shorts,sports & fitness,Yoga,4.4,37,NaN,NaN

In [12]:
df = df.dropna(subset=['actual_price'])
df. head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,"₹34,490","₹67,790"

In [13]:
empty_actual_price = df[df['actual_price'].isnull()]
empty_actual_price

Empty DataFrame
Columns: [name, main_category, sub_category, ratings, no_of_ratings, discount_price, actual_price]
Index: []

In [14]:
empty_discount_price = df[df['discount_price'].isnull()]
empty_discount_price

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
126,"Hitachi 1.5 Ton 5 Star Window AC (Copper, Dust...",appliances,Air Conditioners,2.7,10,NaN,"₹49,300"
137,"Portable Air Conditioner,Office Air Conditione...",appliances,Air Conditioners,3.2,303,NaN,"₹7,250"
207,Voltas 1.5 Ton 3 Star Window AC (Copper 183CYA...,appliances,Air Conditioners,4.1,"1,832",NaN,"₹31,750"
212,"FANCISUN Portable Air Conditioner,Personal Air...",appliances,Air Conditioners,NaN,NaN,NaN,"₹8,980"
213,"BENBOAR Portable Air Conditioner Fan, Desktop ...",appliances,Air Conditioners,3.3,24,NaN,"₹4,969"
...,...,...,...,...,...,...,...
551526,"Nivia 2434 Polyester Women Jacket, X-Large (Tu...",sports & fitness,Yoga,5.0,2,NaN,"₹1,433"
551535,"Nivia 2367-3 Hydra-2 Polyester Training Tee, A...",sports & fitness,Yoga,4.0,8,NaN,₹680
551536,"Nivia 2365-3 Hydra-1 Polyester Training Tee, A...",sports & fitness,Yoga,3.2,7,NaN,₹507
551542,Adidas Men's Flat,sports & fitness,Yoga,NaN,NaN,NaN,"₹2,699"
551567,Adidas Women's Cotton Hooded Neck Sweatshirt,sports & fitness,Yoga,3.9,3,NaN,"₹4,799"

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 533772 entries, 0 to 551584
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            533772 non-null  object
 1   main_category   533772 non-null  object
 2   sub_category    533772 non-null  object
 3   ratings         369030 non-null  object
 4   no_of_ratings   369030 non-null  object
 5   discount_price  490422 non-null  object
 6   actual_price    533772 non-null  object
dtypes: object(7)
memory usage: 32.6+ MB

In [16]:
# check for duplicates in name
duplicates = df[df.duplicated(['name'], keep=False)]
duplicates

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,"₹34,490","₹67,790"
...,...,...,...,...,...,...,...
551561,More & More Dancing Panda Printed Unisex Hoodi...,sports & fitness,Yoga,3.9,271,₹799,"₹2,499"
551562,More & More Dancing Panda Printed Unisex Hoodi...,sports & fitness,Yoga,3.9,271,₹799,"₹2,499"
551568,Adidas Men's Standard,sports & fitness,Yoga,3.4,16,"₹1,349","₹4,299"
551572,Amazon Brand - Symactive Men Shorts,sports & fitness,Yoga,5.0,2,₹655.04,"₹2,399"
551578,Puma Women Sweatshirt,sports & fitness,Yoga,NaN,NaN,"₹1,439","₹2,999"

In [17]:
df = df.drop_duplicates(subset=['name'], keep='first')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 384827 entries, 0 to 551584
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            384827 non-null  object
 1   main_category   384827 non-null  object
 2   sub_category    384827 non-null  object
 3   ratings         263093 non-null  object
 4   no_of_ratings   263093 non-null  object
 5   discount_price  350961 non-null  object
 6   actual_price    384827 non-null  object
dtypes: object(7)
memory usage: 23.5+ MB

In [18]:
df = df.reset_index(drop=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384827 entries, 0 to 384826
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            384827 non-null  object
 1   main_category   384827 non-null  object
 2   sub_category    384827 non-null  object
 3   ratings         263093 non-null  object
 4   no_of_ratings   263093 non-null  object
 5   discount_price  350961 non-null  object
 6   actual_price    384827 non-null  object
dtypes: object(7)
memory usage: 20.6+ MB

In [19]:
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,"₹34,490","₹67,790"

In [20]:
df['name'].loc[0]

'Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1 Convertible, Copper, Anti-Viral + Pm 2.5 Filter, 2023 Model, White, Gls18I3...'

In [21]:
df['name'] = df['name'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384827 entries, 0 to 384826
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            384827 non-null  object
 1   main_category   384827 non-null  object
 2   sub_category    384827 non-null  object
 3   ratings         263093 non-null  object
 4   no_of_ratings   263093 non-null  object
 5   discount_price  350961 non-null  object
 6   actual_price    384827 non-null  object
dtypes: object(7)
memory usage: 20.6+ MB

In [ ]:
truncated_names = df[df['name'].str.endswith('...')]
truncated_names

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,"₹37,990","₹68,990"
6,Lloyd 1.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"1,097","₹29,999","₹49,990"
...,...,...,...,...,...,...,...
384774,"ADAM WHITE Unisex Printed Cotton Hoodies, Swea...",sports & fitness,Yoga,4.0,29,₹699,"₹1,299"
384792,Fitventure Anti Skid Yoga Belt for Stretching ...,sports & fitness,Yoga,3.6,4,₹299,₹599
384805,ManHood Men's Synthetic Lycra Regular Fit Stre...,sports & fitness,Yoga,5.0,1,₹599,"₹1,399"
384816,ELEG & STILANCE Fitness Workout Shorts Women E...,sports & fitness,Yoga,3.2,11,₹498,₹899
384821,"Obsessions Reversible Printed Yoga Mat,Anti-Sl...",sports & fitness,Yoga,NaN,NaN,"₹1,320","₹1,650"

In [26]:
truncated_names.head(10)

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,"₹37,990","₹68,990"
6,Lloyd 1.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"1,097","₹29,999","₹49,990"
7,Lloyd 1.5 Ton 5 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.3,"1,494","₹39,990","₹67,990"
8,Carrier 1 Ton 3 Star AI Flexicool Inverter Spl...,appliances,Air Conditioners,4.1,674,"₹30,990","₹58,190"
10,"Daikin 1 Ton 3 Star Inverter Split AC (Copper,...",appliances,Air Conditioners,4.2,558,"₹32,990","₹48,200"
12,Panasonic 1.5 Ton 5 Star Wi-Fi Inverter Smart ...,appliances,Air Conditioners,4.3,"5,073","₹45,990","₹63,400"
13,Carrier 1.5 Ton 5 Star AI Flexicool Inverter S...,appliances,Air Conditioners,4.0,568,"₹41,999","₹78,490"

In [27]:
dibuang = df[~df['name'].str.endswith('...')]
dibuang.head(10)

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,"₹34,490","₹67,790"
5,Voltas 1.4 Ton 3 Star Inverter Split AC(Copper...,appliances,Air Conditioners,4.0,"1,666","₹31,990","₹70,990"
9,"Voltas 1.5 Ton, 5 Star, Inverter Split AC(Copp...",appliances,Air Conditioners,4.0,801,"₹37,999","₹73,990"
11,Daikin 1.5 Ton 5 Star Inverter Split AC (Coppe...,appliances,Air Conditioners,4.1,730,"₹44,990","₹67,200"
18,Godrej 1 Ton 3 Star Inverter Split Ac Model 20...,appliances,Air Conditioners,3.9,268,"₹29,490","₹42,900"
24,Lloyd 1.5 Ton 3 Star Fixed Speed Window Ac (Co...,appliances,Air Conditioners,NaN,NaN,"₹27,440","₹47,990"
26,"Voltas 1.5 Ton 5 Star, Inverter Window AC (Cop...",appliances,Air Conditioners,3.8,360,"₹36,700","₹49,990"
36,"Daikin 1 Ton 5 Star Inverter Split AC (Copper,...",appliances,Air Conditioners,4.1,94,"₹38,499","₹55,500"
41,Daikin 1.5 Ton 3 Star Fixed Speed Split AC (Co...,appliances,Air Conditioners,4.1,536,"₹37,800","₹55,600"
48,AmazonBasics 1.5 Ton 5 Star Inverter Split AC ...,appliances,Air Conditioners,3.7,"1,195","₹32,990","₹56,990"

In [28]:
dibuang.info()

<class 'pandas.core.frame.DataFrame'>
Index: 294490 entries, 4 to 384826
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            294490 non-null  object
 1   main_category   294490 non-null  object
 2   sub_category    294490 non-null  object
 3   ratings         198522 non-null  object
 4   no_of_ratings   198522 non-null  object
 5   discount_price  263792 non-null  object
 6   actual_price    294490 non-null  object
dtypes: object(7)
memory usage: 18.0+ MB

In [39]:
df['name'] = df['name'].str.replace('...', ')', regex=False)
df.head()

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,"₹34,490","₹67,790"

In [40]:
df.loc[0, 'name']

'Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1 Convertible, Copper, Anti-Viral + Pm 2.5 Filter, 2023 Model, White, Gls18I3)'

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384827 entries, 0 to 384826
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            384827 non-null  object
 1   main_category   384827 non-null  object
 2   sub_category    384827 non-null  object
 3   ratings         263093 non-null  object
 4   no_of_ratings   263093 non-null  object
 5   discount_price  350961 non-null  object
 6   actual_price    384827 non-null  object
dtypes: object(7)
memory usage: 20.6+ MB

In [42]:
df['main_category'] = df['main_category'].astype(str)
df['sub_category'] = df['sub_category'].astype(str)

In [43]:
# Check for missing values in main_category and sub_category
missing_main_category = df[df['main_category'].isnull()]
missing_sub_category = df[df['sub_category'].isnull()]
missing_main_category, missing_sub_category

(Empty DataFrame
 Columns: [name, main_category, sub_category, ratings, no_of_ratings, discount_price, actual_price]
 Index: [],
 Empty DataFrame
 Columns: [name, main_category, sub_category, ratings, no_of_ratings, discount_price, actual_price]
 Index: [])

In [46]:
# check for missing values in rating and no_of_ratings
missing_ratings = df[df['ratings'].isnull()]
missing_ratings

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
24,Lloyd 1.5 Ton 3 Star Fixed Speed Window Ac (Co...,appliances,Air Conditioners,NaN,NaN,"₹27,440","₹47,990"
50,Samsung 1 Ton 5 Star Inverter Split AC (Copper...,appliances,Air Conditioners,NaN,NaN,"₹36,999","₹57,990"
57,Haier 1.5 Ton 3 Star Frost Self Clean Inverter...,appliances,Air Conditioners,NaN,NaN,"₹32,990","₹64,000"
69,Lloyd 2.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,NaN,NaN,"₹46,000","₹77,990"
73,"Voltas 1.5 Ton 3 Star, Fixed Speed Window AC (...",appliances,Air Conditioners,NaN,NaN,"₹29,990","₹42,990"
...,...,...,...,...,...,...,...
384765,The Yogis Iyengar Wall Yoga Ropes full Set of ...,sports & fitness,Yoga,NaN,NaN,"₹1,699","₹1,999"
384767,Men's Regular FIT Dont Quit Printed Cotton Hoodie,sports & fitness,Yoga,NaN,NaN,₹549,₹899
384814,Amazon Brand - Symactive Men's Activewear Gym ...,sports & fitness,Yoga,NaN,NaN,₹699,"₹2,199"
384818,Just rider Arm Sleeves UV Protection for Drivi...,sports & fitness,Yoga,NaN,NaN,₹219,₹699
384821,"Obsessions Reversible Printed Yoga Mat,Anti-Sl...",sports & fitness,Yoga,NaN,NaN,"₹1,320","₹1,650"

In [47]:
missing_no_of_ratings = df[df['no_of_ratings'].isnull()]
missing_no_of_ratings

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
24,Lloyd 1.5 Ton 3 Star Fixed Speed Window Ac (Co...,appliances,Air Conditioners,NaN,NaN,"₹27,440","₹47,990"
50,Samsung 1 Ton 5 Star Inverter Split AC (Copper...,appliances,Air Conditioners,NaN,NaN,"₹36,999","₹57,990"
57,Haier 1.5 Ton 3 Star Frost Self Clean Inverter...,appliances,Air Conditioners,NaN,NaN,"₹32,990","₹64,000"
69,Lloyd 2.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,NaN,NaN,"₹46,000","₹77,990"
73,"Voltas 1.5 Ton 3 Star, Fixed Speed Window AC (...",appliances,Air Conditioners,NaN,NaN,"₹29,990","₹42,990"
...,...,...,...,...,...,...,...
384765,The Yogis Iyengar Wall Yoga Ropes full Set of ...,sports & fitness,Yoga,NaN,NaN,"₹1,699","₹1,999"
384767,Men's Regular FIT Dont Quit Printed Cotton Hoodie,sports & fitness,Yoga,NaN,NaN,₹549,₹899
384814,Amazon Brand - Symactive Men's Activewear Gym ...,sports & fitness,Yoga,NaN,NaN,₹699,"₹2,199"
384818,Just rider Arm Sleeves UV Protection for Drivi...,sports & fitness,Yoga,NaN,NaN,₹219,₹699
384821,"Obsessions Reversible Printed Yoga Mat,Anti-Sl...",sports & fitness,Yoga,NaN,NaN,"₹1,320","₹1,650"

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384827 entries, 0 to 384826
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            384827 non-null  object
 1   main_category   384827 non-null  object
 2   sub_category    384827 non-null  object
 3   ratings         263093 non-null  object
 4   no_of_ratings   263093 non-null  object
 5   discount_price  350961 non-null  object
 6   actual_price    384827 non-null  object
dtypes: object(7)
memory usage: 20.6+ MB

In [51]:
non_numeric_ratings = df[pd.to_numeric(df['ratings'], errors='coerce').isnull()]
non_numeric_ratings

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
24,Lloyd 1.5 Ton 3 Star Fixed Speed Window Ac (Co...,appliances,Air Conditioners,NaN,NaN,"₹27,440","₹47,990"
50,Samsung 1 Ton 5 Star Inverter Split AC (Copper...,appliances,Air Conditioners,NaN,NaN,"₹36,999","₹57,990"
57,Haier 1.5 Ton 3 Star Frost Self Clean Inverter...,appliances,Air Conditioners,NaN,NaN,"₹32,990","₹64,000"
69,Lloyd 2.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,NaN,NaN,"₹46,000","₹77,990"
73,"Voltas 1.5 Ton 3 Star, Fixed Speed Window AC (...",appliances,Air Conditioners,NaN,NaN,"₹29,990","₹42,990"
...,...,...,...,...,...,...,...
384799,Amazon Brand - Symactive Men's Activewear Gym ...,sports & fitness,Yoga,NaN,FREE Delivery by Amazon,₹699,"₹2,199"
384800,Amazon Brand - Symactive Men's Activewear Gym ...,sports & fitness,Yoga,NaN,FREE Delivery by Amazon,₹651.01,"₹2,399"
384814,Amazon Brand - Symactive Men's Activewear Gym ...,sports & fitness,Yoga,NaN,NaN,₹699,"₹2,199"
384818,Just rider Arm Sleeves UV Protection for Drivi...,sports & fitness,Yoga,NaN,NaN,₹219,₹699
384821,"Obsessions Reversible Printed Yoga Mat,Anti-Sl...",sports & fitness,Yoga,NaN,NaN,"₹1,320","₹1,650"

In [60]:
# Define a function to replace specific strings with NaN
def replace_with_nan(x):
    if isinstance(x, str) and (
        x.startswith("Get") or x.startswith("Free") or x.startswith("FREE") or x.startswith("₹")
    ):
        return np.nan
    else:
        return x

# Apply the function to the 'ratings' column
df['ratings'] = df['ratings'].apply(replace_with_nan)

# Verify the changes
df['ratings'].head()

0    4.2
1    4.2
2    4.2
3    4.0
4    4.1
Name: ratings, dtype: object

In [61]:
df['ratings'] = df['ratings'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 384827 entries, 0 to 384826
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            384827 non-null  object
 1   main_category   384827 non-null  object
 2   sub_category    384827 non-null  object
 3   ratings         257527 non-null  float64
 4   no_of_ratings   263093 non-null  object
 5   discount_price  350961 non-null  object
 6   actual_price    384827 non-null  object
dtypes: float64(1), object(6)
memory usage: 20.6+ MB

In [62]:
df.head(10)

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,"₹34,490","₹67,790"
5,Voltas 1.4 Ton 3 Star Inverter Split AC(Copper...,appliances,Air Conditioners,4.0,"1,666","₹31,990","₹70,990"
6,Lloyd 1.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"1,097","₹29,999","₹49,990"
7,Lloyd 1.5 Ton 5 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.3,"1,494","₹39,990","₹67,990"
8,Carrier 1 Ton 3 Star AI Flexicool Inverter Spl...,appliances,Air Conditioners,4.1,674,"₹30,990","₹58,190"
9,"Voltas 1.5 Ton, 5 Star, Inverter Split AC(Copp...",appliances,Air Conditioners,4.0,801,"₹37,999","₹73,990"

In [65]:
# Find rows where 'no_of_ratings' contains non-numeric values
non_numeric_no_of_ratings = df[pd.to_numeric(df['no_of_ratings'], errors='coerce').isnull()]

# Display rows with non-numeric values in 'no_of_ratings'
non_numeric_no_of_ratings

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,"1,206","₹34,490","₹61,990"
5,Voltas 1.4 Ton 3 Star Inverter Split AC(Copper...,appliances,Air Conditioners,4.0,"1,666","₹31,990","₹70,990"
6,Lloyd 1.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,"1,097","₹29,999","₹49,990"
...,...,...,...,...,...,...,...
384799,Amazon Brand - Symactive Men's Activewear Gym ...,sports & fitness,Yoga,NaN,NaN,₹699,"₹2,199"
384800,Amazon Brand - Symactive Men's Activewear Gym ...,sports & fitness,Yoga,NaN,NaN,₹651.01,"₹2,399"
384814,Amazon Brand - Symactive Men's Activewear Gym ...,sports & fitness,Yoga,NaN,NaN,₹699,"₹2,199"
384818,Just rider Arm Sleeves UV Protection for Drivi...,sports & fitness,Yoga,NaN,NaN,₹219,₹699
384821,"Obsessions Reversible Printed Yoga Mat,Anti-Sl...",sports & fitness,Yoga,NaN,NaN,"₹1,320","₹1,650"

In [64]:
# Define a function to replace specific strings with random integers
def replace_with_nan_no_of_ratings(x):
    if isinstance(x, str) and (
        x.startswith("Usually dispatched") or x.startswith("Only") or x.startswith("Free") or x.startswith("This item") or x.startswith("FREE Delivery")
    ):
        return np.nan
    else:
        return x

# Apply the function to the 'no_of_ratings' column
df['no_of_ratings'] = df['no_of_ratings'].apply(replace_with_nan_no_of_ratings)

In [70]:
df['no_of_ratings'] = df['no_of_ratings'].str.replace(',', '')
df.head(10)

,name,main_category,sub_category,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,2255,"₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.2,2948,"₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,4.2,1206,"₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,4.1,630,"₹34,490","₹67,790"
5,Voltas 1.4 Ton 3 Star Inverter Split AC(Copper...,appliances,Air Conditioners,4.0,1666,"₹31,990","₹70,990"
6,Lloyd 1.0 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.2,1097,"₹29,999","₹49,990"
7,Lloyd 1.5 Ton 5 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,4.3,1494,"₹39,990","₹67,990"
8,Carrier 1 Ton 3 Star AI Flexicool Inverter Spl...,appliances,Air Conditioners,4.1,674,"₹30,990","₹58,190"
9,"Voltas 1.5 Ton, 5 Star, Inverter Split AC(Copp...",appliances,Air Conditioners,4.0,801,"₹37,999","₹73,990"